# Q1.

In [1]:
import numpy as np

In [2]:
x=np.arange(2,50,3)

In [3]:
print(type(x))
print(x)

<class 'numpy.ndarray'>
[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Q2.


In [4]:
list1=[]
print("ENTER LIST 1")
for i in range (5):
    ele=int(input())
    list1.append(ele)
print(list1)

ENTER LIST 1
12
34
22
55
66
[12, 34, 22, 55, 66]


In [5]:
list2=[]
print("ENTER LIST 2")
for i in range(5):
    ele=int(input())
    list2.append(ele)
print (list2)

ENTER LIST 2
99
11
23
34
55
[99, 11, 23, 34, 55]


In [6]:
arr1=np.array(list1)
print(arr1)
print(type(arr1))

[12 34 22 55 66]
<class 'numpy.ndarray'>


In [7]:
arr2=np.array(list2)
print(arr2)
print(type(arr2))

[99 11 23 34 55]
<class 'numpy.ndarray'>


In [8]:
arc=np.concatenate((arr1,arr2))
print(arc)
print(type(arc))

[12 34 22 55 66 99 11 23 34 55]
<class 'numpy.ndarray'>


In [9]:
srt=np.sort(arc)
print(srt)

[11 12 22 23 34 34 55 55 66 99]


# Q3.

In [10]:
arr=np.array([[1,2,3], [4,5,6], [7,8,9]])

In [14]:
print ("Number of Dimensions are: ",arr.ndim)
print ("Size of Array is: ", arr.size)
print ("shape of Array is:", arr.shape)

Number of Dimensions are:  2
Size of Array is:  9
shape of Array is: (3, 3)


# Q4.

In [20]:
a=np.arange(12)

In [21]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
a2=a[np.newaxis,:]

In [26]:
print(a2.shape)


(1, 12)


# Q5.

In [28]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print("Vertical stacking:\n", np.vstack((a, b))) 
print("\nHorizontal stacking:\n", np.hstack((a, b)))


Vertical stacking:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizontal stacking:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Q6.

In [32]:
arr=np.array([1,1,22,33,44,1,99,55,66,22,1,77,99,1,33,99,22,101,55])
print("original Array is",arr)
uniqueValues, occurCount = np.unique(arr, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)

original Array is [  1   1  22  33  44   1  99  55  66  22   1  77  99   1  33  99  22 101
  55]
Unique Values :  [  1  22  33  44  55  66  77  99 101]
Occurrence Count :  [5 3 2 1 2 1 1 3 1]


# END, ENJOYED IT.